name: tnt_simple
channels:
  - defaults
dependencies:
    - conda-forge::hdbscan
    - ipykernel
    - numpy
    - pandas
    - pip
    - python>=3.7,<3.11
    - scikit-learn
    - scipy
    - setuptools
    - wheel
    - pip:
        - bokeh
        - ipympl
        - ipywidgets
        - matplotlib<3.6
        - panel
        - tqdm
        - umap-learn[plot]
        - nbformat
        - nbclient
        - git+https://github.com/TutteInstitute/Vectorizers.git
        - git+https://github.com/TutteInstitute/thisnotthat.git

name: vectorizers_playground
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - -e .   # conda >= 4.4 only
    - python-dotenv
    - gdown
    - sentence-transformers
    - umap-learn
    - hdbscan
    - wordcloud
    - git+https://github.com/TutteInstitute/vectorizers
  - bokeh
  - click
  - colorcet     # umap-learn[plot]
  - coveralls
  - datashader   # umap-learn[plot]
  - fsspec
  - gensim
  - git>=2.5     # for git worktree template updating
  - holoviews    # umap-learn[plot]
  - joblib
  - jupyter
  - jupyterlab
  - matplotlib
  - nb_conda_kernels#<2.2.0  # nb_conda_kernels issue #158
  - pandas
  - pathlib
  - pytest
  - requests
  - scikit-image   # umap-learn[plot]
  - scikit-learn
  - scipy
  - seaborn
